
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "slotguard-rpi"
BBFILE_PATTERN_slotguard-rpi = "^${LAYERDIR}/"

BBFILE_PRIORITY_slotguard-rpi = "15"

LAYERDEPENDS_slotguard-rpi = "core slotguard raspberrypi rauc"

LAYERSERIES_COMPAT_slotguard-rpi = "wrynose"

WKS_SEARCH_PATH:append = ":${LAYERDIR}/files/wic"
