[system]
compatible=slotguard-rpi-UNCONFIGURED
bootloader=uboot

data-directory=/data/rauc
statusfile=/data/rauc/slot.status

mountprefix=/run/rauc

bundle-formats=-plain

boot-attempts=3
boot-attempts-primary=3

[keyring]
path=/usr/lib/rauc/ca.cert.pem
use-bundle-signing-time=true

[slot.rootfs.0]
device=/dev/mmcblk0p2
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/mmcblk0p3
type=ext4
bootname=B
